### ISSUE TITLE
Overriding TARGET_ARCH is problematic

### ISSUE THREAD

**Issue by s-hemer** [lucimber/meta-openjdk-temurin#46]
Overriding TARGET_ARCH (https://github.com/lucimber/meta-openjdk-temurin/blob/d78a29cbc2bd1d09e958349fab1c71075faacf37/recipes-core/openjdk-17-jre/openjdk-17-jre_17.0.10%2B7.bb#L7C1-L7C29) does not build when using compiler tunes like i.e. "crypto". That results in sstate manifests commonly named  ```manifest-cortexa53-crypto-*``` in my case, yet the JRE package searches them only for ```manifest-cortexa53-*```.

**Comment by sebveit** [comment]
Sorry for the late reply. Thanks for reporting that issue. I'll look into it!

**Comment by sebveit** [comment]
Sorry for the late reply! Have you already figured this one out? Do you have a workaround? I'm thinking about rewriting the recipes but I'm unsure...

**Comment by sebveit** [comment]
The lack of if else statements or related conditional statements in the recipe syntax is preventing me from adapting the current recipes in a way that your problem can be solved. Therefore it would be nice if that obstacle is still present or not. Thanks!

**Comment by s-hemer** [comment]
Hey Sebastian, thanks for looking into it. I just deleted that line. For just building a Yocto image that worked. Didn't do intensive testing with the JDK on the machine.

When I have a look at the OVERRIDES, there is pretty much included if the statement is not present
```
OVERRIDES="runtime-gnu:toolchain-gcc:linux:aarch64:pn-openjdk-17-jre:aarch64:armv8a:use-nxp-bsp:imx-generic-bsp:imx-nxp-bsp:imxdrm:imxvpu:imxgpu:imxgpu2d:imxgpu3d:mx8-generic-bsp:mx8-nxp-bsp:mx8m-generic-bsp:mx8m-nxp-bsp:mx8mm-generic-bsp:mx8mm-nxp-bsp:phyboard-polis-imx8mm-5:ampliphy-vendor-xwayland:class-target:libc-glibc:forcevariable
```
So all this is enforced to be dropped. Why? Why only use OVERRIDES that equal TARGET_ARCH (in this case ```aarch64```)?

**Comment by sebveit** [comment]
Ohhhh now I get it!

The recipe is resetting `OVERRIDES`, instead of appending to it. Yeah, that seems to be a mistake! Sorry for that!

Can you tell me what you have written in your `local.conf` for using the crypto "feature", because I can't find information about it in the Yocto documentation. I think it's related to `TUNE_FEATURES` but I'm not sure.

**Comment by sebveit** [comment]
Nevermind, I figured out that `OVERRIDES` is no longer needed. Therefore, I'm going to patch all recipes accordingly. Thanks for bringing that behaviour to my attention!

Feel free to open an issue if you encounter other bugs/problems!

**Comment by s-hemer** [comment]
Thanks for having a deeper look and confirming my hot fix that ``OVERRIDES``` can be just left away. Waiting forward for #48 to fix it finally.
